services:
  backend:
    build: ./back-end
    container_name: symfony_backend
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/var/www/html
    command: php -S 0.0.0.0:8000 -t public

  frontend:
    build: ./front-end
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: npm run dev -- --host